Fix mb_unittest.py for Windows
The tests in mb_unittest.py carefully mock the file system entirely, and
then do Linux and Windows tests on both platforms. That's all great, but
somehow when run on Windows we were getting various errors including
this one:

    KeyError: '/fake_src/out/Default/C:\\src\\temp\\mb_test/task.json'

That path does not look good. The root cause is that crrev.com/c/2378273
added a TempDir function and that function did this:

    tmp_dir = os.path.join(tempfile.gettempdir(), 'mb_test')

That is, it used OS functions to get the temporary directory and to do
path joining. When testing the Linux functionality on Windows the
_AbsPath would look at 'C:\\src\\temp\\mb_test' and determine that it
was not a relative directory so it would prepend the current working
directory, and the world falls apart.

The fix is to mock the temporary directory as well. It's anticlimactic
really.

The fact that these tests worked on Linux was just luck (good or bad,
you decide). With this fixed the presubmits only have one minor
Windows-specific failure remaining.

Bug: 1309977
Change-Id: I4988b6d1b56e2da50196dfc3f339c4e12b80045c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3659032
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1006200}
NOKEYCHECK=True
GitOrigin-RevId: 5d8d1585b8af955b4866b1f7c88a32a8959b5e9f