Disable ML inliner for Cronet builders that use Mainline Clang
MLGO inliner requires Clang to be built with specific flags. Cronet builders use prebuilt Mainline Clang which does not compile with these flags. Therefore, we have to disable ML inliner for Cronet builders.

Test:
Setting GN args with use_ml_inliner = false:
~/chromium/src$ autoninja -C out/Release net_unittests__library
ninja: Entering directory `out/Release'
[96/96] SOLINK ./libnet_unittests__library.so

Setting GN args with use_ml_inliner = true:
~/chromium/src$ autoninja -C out/Release net_unittests__library
error: Could not setup Inlining Advisor for the requested mode and/or options

Bug: 1468680, 1463752
Change-Id: Id71050ef66d2047008b7f8c6a1118b9a3e9cf301
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4729979
Reviewed-by: Hans Wennborg <hans@chromium.org>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Trung Nguyen <tne@google.com>
Cr-Commit-Position: refs/heads/main@{#1177466}
NOKEYCHECK=True
GitOrigin-RevId: 188f015fcf85330776094e23723809e58320c73e